### ISSUE TITLE
Ubuntu Network: netplan

### ISSUE THREAD

**Issue by nguyenvulong** [nguyenvulong/QA#13]
since `17.10` release, [netplan ](https://netplan.io/examples/)is the default network management tool for Ubuntu
make sure to use DNS (`nameservers`)

**Examples (`yaml` file)**
DHCP
```

network:
    version: 2
    renderer: networkd
    ethernets:
        enp3s0:
            dhcp4: true
```

Static
```
network:
    version: 2
    renderer: networkd
    ethernets:
        enp3s0:
            addresses:
                - 10.10.10.2/24
            nameservers:
                search: [mydomain, otherdomain]
                addresses: [10.10.10.1, 1.1.1.1]
            routes:
                - to: default
                  via: 10.10.10.1
```

Wi-Fi
```
network:
    version: 2
    renderer: networkd
    wifis:
        wlp2s0b1:
            dhcp4: no
            dhcp6: no
            addresses: [192.168.0.21/24]
            nameservers:
                addresses: [192.168.0.1, 8.8.8.8]
            access-points:
                "network_ssid_name":
                    password: "**********"
            routes:
                - to: default
                  via: 192.168.0.1
```
